/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/components/DogCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/DogDetailModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/FilterControls`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/MatchModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pagination`; params?: Router.UnknownInputParams; } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useDogSearch`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFavorites`; params?: Router.UnknownInputParams; } | { pathname: `/providers/auth`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/api`; params?: Router.UnknownOutputParams; } | { pathname: `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/components/DogCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/DogDetailModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FilterControls`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MatchModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Pagination`; params?: Router.UnknownOutputParams; } | { pathname: `/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useDogSearch`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useFavorites`; params?: Router.UnknownOutputParams; } | { pathname: `/providers/auth`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/api${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/components/DogCard${`?${string}` | `#${string}` | ''}` | `/components/DogDetailModal${`?${string}` | `#${string}` | ''}` | `/components/FilterControls${`?${string}` | `#${string}` | ''}` | `/components/Header${`?${string}` | `#${string}` | ''}` | `/components/MatchModal${`?${string}` | `#${string}` | ''}` | `/components/Pagination${`?${string}` | `#${string}` | ''}` | `/constants${`?${string}` | `#${string}` | ''}` | `/hooks/useDogSearch${`?${string}` | `#${string}` | ''}` | `/hooks/useFavorites${`?${string}` | `#${string}` | ''}` | `/providers/auth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/components/DogCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/DogDetailModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/FilterControls`; params?: Router.UnknownInputParams; } | { pathname: `/components/Header`; params?: Router.UnknownInputParams; } | { pathname: `/components/MatchModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/Pagination`; params?: Router.UnknownInputParams; } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useDogSearch`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useFavorites`; params?: Router.UnknownInputParams; } | { pathname: `/providers/auth`; params?: Router.UnknownInputParams; };
    }
  }
}
